---
- name: create rados gateway directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ dir_owner }}"
    group: "{{ dir_group }}"
    mode: "{{ dir_mode }}"
  with_items:
    - /var/lib/ceph/bootstrap-rgw
    - /var/lib/ceph/radosgw
    - /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}
    - "{{ rbd_client_admin_socket_path }}"
  when: instances is not defined

- name: create rados gateway directories for rgw instances
  file:
    path: "/var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ item | default(ansible_hostname) }}"
    state: directory
    owner: "{{ dir_owner }}"
    group: "{{ dir_group }}"
    mode: "{{ dir_mode }}"
  with_items: "{{ instances }}"
  when: instances is defined


- name: copy rados gateway bootstrap key
  copy:
    src: "{{ fetch_directory }}/{{ fsid }}{{ item.name }}"
    dest: "{{ item.name }}"
    owner: "{{ key_owner }}"
    group: "{{ key_group }}"
    mode: "{{ key_mode }}"
  with_items:
    - { name: "/var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring", copy_key: true }
    - { name: "/etc/ceph/{{ cluster }}.client.admin.keyring", copy_key: "{{ copy_admin_key }}" }
  when:
    - cephx
    - item.copy_key|bool

- name: create rados gateway keyring
  command: ceph --cluster {{ cluster }} --name client.bootstrap-rgw --keyring /var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring auth get-or-create client.rgw.{{ ansible_hostname }} osd 'allow rwx' mon 'allow rw' -o /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}/keyring
  args:
    creates: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}/keyring
  changed_when: false
  when: 
    - cephx
    - instances is not defined

- name: create rados gateway keyring for rgw instances
  command: ceph --cluster {{ cluster }} --name client.bootstrap-rgw --keyring /var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring auth get-or-create client.rgw.{{ item | default(ansible_hostname) }} osd 'allow rwx' mon 'allow rw' -o /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ item | default(ansible_hostname) }}/keyring
  args:
    creates: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ item | default(ansible_hostname) }}/keyring
  changed_when: false
  with_items: "{{ instances }}"
  when:
    - cephx
    - instances is defined



- name: set rados gateway key permissions (for or after the infernalis release)
  file:
    path: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}/keyring
    mode: "{{ key_mode }}"
    owner: "{{ key_owner }}"
    group: "{{ key_group }}"
  when: 
    - cephx
    - instances is not defined

- name: create rados gateway keyring for rgw instances
  command: ceph --cluster {{ cluster }} --name client.bootstrap-rgw --keyring /var/lib/ceph/bootstrap-rgw/{{ cluster }}.keyring auth get-or-create client.rgw.{{ item | default(ansible_hostname) }} osd 'allow rwx' mon 'allow rw' -o /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ item | default(ansible_hostname) }}/keyring
  args:
    creates: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ item | default(ansible_hostname) }}/keyring
  changed_when: false
  with_items: "{{ instances }}"
  when:
    - cephx
    - instances is defined


- name: ensure ceph-radosgw systemd unit file is present
  command: chkconfig --add ceph-radosgw
  args:
    creates: /var/run/systemd/generator.late/ceph-radosgw.service
  when:
    - use_systemd
    - ceph_release_num.{{ ceph_release }} < ceph_release_num.infernalis
    - not rgw_containerized_deployment

- name: activate rados gateway with upstart
  file:
    path: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}/{{ item }}
    state: touch
    owner: "{{ activate_file_owner }}"
    group: "{{ activate_file_group }}"
    mode: "{{ activate_file_mode }}"
  with_items:
    - done
    - upstart
  changed_when: false
  when:
    - ansible_distribution == "Ubuntu"
    - not use_systemd
    - not rgw_containerized_deployment

- name: activate rados gateway with sysvinit
  file:
    path: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ ansible_hostname }}/{{ item }}
    state: touch
    owner: "{{ activate_file_owner }}"
    group: "{{ activate_file_group }}"
    mode: "{{ activate_file_mode }}"
  with_items:
    - done
    - sysvinit
  changed_when: false
  when:
    - ansible_distribution != "Ubuntu"
    - instances is not defined
    - not rgw_containerized_deployment

- name: activate rados gateway with sysvinit for rgw instances
  file:
    path: /var/lib/ceph/radosgw/{{ cluster }}-rgw.{{ item[0] | default(ansible_hostname) }}/{{ item[1] }}
    state: touch
    owner: "{{ activate_file_owner }}"
    group: "{{ activate_file_group }}"
    mode: "{{ activate_file_mode }}"
  with_nested:
    - "{{ instances }}"
    - [ done, sysvinit]
  changed_when: false
  when:
    - ansible_distribution != "Ubuntu"
    - instances is defined
    - not rgw_containerized_deployment


- name: generate rados gateway sudoers file
  template:
    src: ceph.j2
    dest: /etc/sudoers.d/ceph
    owner: root
    group: root
    mode: 0400
  when: ansible_distribution != "Ubuntu"
