---
# Use systemd to manage container on Atomic host
- name: generate systemd unit file
  become: true
  template:
    src: "{{ playbook_dir }}/roles/ceph-rgw/templates/ceph-rgw.service.j2"
    dest: /usr/lib/systemd/system/ceph-radosgw@.service
    owner: "root"
    group: "root"
    mode: "0644"
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CoreOS'

- name: reload systemd unit files
  shell: systemctl daemon-reload
  changed_when: false
  failed_when: false
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'CoreOS'

- name: systemd start rgw container
  service:
    name: ceph-radosgw@rgw.{{ item }}
    state: started
    enabled: yes
  with_items: "{{ instances }}"
  changed_when: false
