---
# tasks file for serv-keepalived
- name: install keepalived and ipvsadm
  yum: name={{item}} state=present
  with_items:
    - keepalived
    - ipvsadm

- name: ip_forward
  shell: |
      echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
      sysctl -p
      firewall-cmd --direct --permanent --add-rule ipv4 filter INPUT 0 --in-interface {{ vrrp_instances_devices }} --destination 224.0.0.18 --protocol vrrp -j ACCEPT
      firewall-cmd --direct --permanent --add-rule ipv4 filter OUTPUT 0 --out-interface {{ vrrp_instances_devices }} --destination 224.0.0.18 --protocol vrrp -j ACCEPT
      firewall-cmd --zone=public --add-port=112/tcp  --permanent


- name: server port
  shell: |
      firewall-cmd --zone=public --add-port={{ item.port }}/tcp  --permanent
      firewall-cmd --reload
  with_items: "{{ virtual_server_groups }}"


- name: keepalived conf
  template: src=keepalived.j2
            dest=/etc/keepalived/keepalived.conf
            owner=root
            group=root
            mode=644
            backup=true

- name: start and enable keepalived.service
  service: name=keepalived.service state=started enabled=yes